# Generated by Django 2.2.28 on 2024-03-22 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=128, unique=True)),
                ('past_owners', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lastSave', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('copyCount', models.PositiveIntegerField(default=0)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotas.Subject')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotas.UserProfile')),
            ],
        ),
    ]
