# Generated by Django 2.2.28 on 2024-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0004_auto_20240216_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteTitle', models.CharField(max_length=128)),
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
