# Generated by Django 2.2.28 on 2024-03-12 18:28

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='fileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='lastSave',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
