# Generated by Django 2.2.28 on 2024-03-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0006_auto_20240312_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
