# Generated by Django 2.2.28 on 2024-03-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0007_remove_userprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='lastSave',
        ),
    ]
