# Generated by Django 2.2.28 on 2024-03-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0007_auto_20240321_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
