# Generated by Django 2.2.28 on 2024-03-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0009_note_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='userID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
