# Generated by Django 2.2.28 on 2024-03-21 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0010_auto_20240321_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastSave',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
