# Generated by Django 2.2.28 on 2024-03-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0011_auto_20240321_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='past_owners',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
