# Generated by Django 2.2.28 on 2024-03-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotas', '0010_auto_20240321_2156'),
        ('anotas', '0012_auto_20240322_0005'),
    ]

    operations = [
    ]
